/* Eigen dialogen: korte alledaagse gesprekken per unidad (1–3, 5–7).
 *
 * Geschreven voor deze app, niet overgenomen uit het boek. Uit "Sí, claro
 * nuevo 1.2" komen enkel de situaties, de woordenschat en de sleutelzinnen
 * (woordenlijst per unidad achteraan het boek, fiche over telefoneren).
 * Elke zin is een apart dialogue-atoom; de tekst bevat titel en situatie. */

// Eén dialoog: tekst + een atoom per regel. lines: [wie, es, nl].
function dialoog(slug, unit, title, nl, lines) {
  const srcLabel = `Eigen dialoog bij unidad ${unit}`;
  const text = `t.${slug}`;
  return {
    text: { [text]: { title, es: '', nl, srcLabel } },
    atoms: lines.map(([who, es, nlLine], i) => ({
      id: `d.${slug}.${i + 1}`,
      kind: 'dialogue',
      theme: `luister-u${unit}`,
      text,
      line: i + 1,
      who,
      es,
      nl: nlLine,
      srcLabel,
    })),
  };
}

const DIALOGEN = [
  /* ---- Unidad 1: Caminando (kleding, kleuren, weer, vergelijken) ---- */
  dialoog('dlg-u1-botas', 1, 'In de schoenwinkel', 'Een klant koopt bergschoenen voor een trektocht in Peru.', [
    ['Dependiente', 'Buenos días, ¿qué desea?', 'Goedendag, wat wenst u?'],
    ['Clienta', 'Busco unas botas de montaña para un viaje a Perú.', 'Ik zoek bergschoenen voor een reis naar Peru.'],
    ['Dependiente', 'Muy bien. ¿Qué número tiene?', 'Heel goed. Welke schoenmaat hebt u?'],
    ['Clienta', 'Tengo el treinta y ocho.', 'Ik heb maat achtendertig.'],
    ['Dependiente', 'Mire, estas son de cuero y muy cómodas.', 'Kijk, deze zijn van leer en heel comfortabel.'],
    ['Clienta', 'Son bonitas, pero ¿cuánto cuestan?', 'Ze zijn mooi, maar hoeveel kosten ze?'],
    ['Dependiente', 'Noventa euros. Estas marrones son más baratas.', 'Negentig euro. Deze bruine zijn goedkoper.'],
    ['Clienta', '¿Son tan cómodas como las otras?', 'Zijn ze even comfortabel als de andere?'],
    ['Dependiente', 'Sí, y además son más ligeras.', 'Ja, en bovendien zijn ze lichter.'],
    ['Clienta', 'Perfecto, me llevo las marrones.', 'Perfect, ik neem de bruine.'],
  ]),
  dialoog('dlg-u1-jersey', 1, 'Een trui kopen', 'In een kledingwinkel zoekt een klant een warme trui.', [
    ['Dependienta', 'Hola, ¿puedo ayudarle?', 'Hallo, kan ik u helpen?'],
    ['Cliente', 'Sí, busco un jersey de lana para el invierno.', 'Ja, ik zoek een wollen trui voor de winter.'],
    ['Dependienta', '¿Qué talla tiene?', 'Welke maat hebt u?'],
    ['Cliente', 'Normalmente, la M.', 'Normaal gezien medium.'],
    ['Dependienta', 'Tenemos este gris y ese azul.', 'We hebben deze grijze en die blauwe.'],
    ['Cliente', 'El azul me gusta más. ¿Dónde está el probador?', 'De blauwe vind ik mooier. Waar is de paskamer?'],
    ['Dependienta', 'Al fondo, a la derecha.', 'Achteraan, rechts.'],
    ['Cliente', 'Me queda un poco pequeño. ¿Lo tiene en una talla más grande?', 'Hij is me wat te klein. Hebt u hem een maat groter?'],
    ['Dependienta', 'Sí, aquí tiene la L.', 'Ja, hier is de large.'],
    ['Cliente', 'Ahora sí, me queda muy bien.', 'Zo is het goed, hij past me heel goed.'],
  ]),
  dialoog('dlg-u1-tiempo', 1, 'Het weer in Cuzco', 'Laura is op reis in Peru en belt met haar broer Marcos in Gent.', [
    ['Marcos', '¡Hola, Laura! ¿Qué tal por Perú?', 'Hallo, Laura! Hoe is het in Peru?'],
    ['Laura', '¡Genial! Estoy en Cuzco y es precioso.', 'Geweldig! Ik ben in Cuzco en het is prachtig.'],
    ['Marcos', '¿Y qué tiempo hace allí?', 'En wat voor weer is het daar?'],
    ['Laura', 'De día hace sol y calor, pero de noche hace mucho frío.', 'Overdag is het zonnig en warm, maar ’s nachts is het heel koud.'],
    ['Marcos', '¿Cuántos grados hace por la noche?', 'Hoeveel graden is het ’s nachts?'],
    ['Laura', 'Unos dos grados. ¡Menos mal que tengo mi jersey de lana!', 'Een graad of twee. Gelukkig heb ik mijn wollen trui bij!'],
    ['Marcos', 'Aquí en Gante está lloviendo otra vez.', 'Hier in Gent regent het alweer.'],
    ['Laura', '¡Como siempre! Aquí llueve menos que en Bélgica.', 'Zoals altijd! Hier regent het minder dan in België.'],
    ['Marcos', '¿Y qué vas a hacer mañana?', 'En wat ga je morgen doen?'],
    ['Laura', 'Voy a empezar el Camino Inca con un grupo.', 'Ik begin met een groep aan het Incapad.'],
    ['Marcos', '¡Qué bien! ¡Haz muchas fotos!', 'Wat goed! Neem veel foto’s!'],
  ]),
  dialoog('dlg-u1-mochila', 1, 'De rugzak inpakken', 'Pablo en Sara maken hun rugzak klaar voor een trektocht in de bergen.', [
    ['Pablo', '¿Ya tienes todo en la mochila?', 'Heb je alles al in je rugzak?'],
    ['Sara', 'Casi. Llevo dos camisetas, un jersey y calcetines.', 'Bijna. Ik neem twee T-shirts, een trui en sokken mee.'],
    ['Pablo', '¿Y el anorak? En la montaña hace viento.', 'En je windjack? In de bergen waait het.'],
    ['Sara', 'Sí, está aquí, encima de las botas.', 'Ja, het ligt hier, boven op de bergschoenen.'],
    ['Pablo', 'No te olvides de la crema solar y las gafas de sol.', 'Vergeet de zonnecrème en je zonnebril niet.'],
    ['Sara', 'Ya están dentro. ¿Llevas tú el papel higiénico?', 'Die zitten er al in. Neem jij het toiletpapier mee?'],
    ['Pablo', 'Sí, y también agua para todo el día.', 'Ja, en ook water voor de hele dag.'],
    ['Sara', '¡Uf! Tu mochila es más pesada que la mía.', 'Oef! Jouw rugzak is zwaarder dan de mijne.'],
    ['Pablo', 'No pasa nada, yo soy más fuerte que tú.', 'Geen probleem, ik ben sterker dan jij.'],
    ['Sara', '¡Ja, ja! Eso lo vamos a ver mañana.', 'Haha! Dat zullen we morgen wel zien.'],
  ]),

  /* ---- Unidad 2: Tengo planes (vrije tijd, afspreken, restaurant) ---- */
  dialoog('dlg-u2-telefono', 2, 'Afspreken aan de telefoon', 'Tomás belt naar Lucía om samen naar de film te gaan; haar moeder neemt op.', [
    ['Madre', '¿Dígame?', 'Hallo?'],
    ['Tomás', 'Hola, buenas tardes. ¿Está Lucía, por favor?', 'Hallo, goedemiddag. Is Lucía er, alstublieft?'],
    ['Madre', '¿De parte de quién?', 'Wie mag ik zeggen?'],
    ['Tomás', 'Soy Tomás, un compañero de clase.', 'Met Tomás, een klasgenoot.'],
    ['Madre', 'Un momento, ahora se pone.', 'Een ogenblikje, ze komt eraan.'],
    ['Lucía', 'Hola, Tomás, ¿qué tal?', 'Hallo, Tomás, hoe gaat het?'],
    ['Tomás', 'Bien. Oye, ¿tienes ganas de ir al cine el sábado?', 'Goed. Zeg, heb je zin om zaterdag naar de film te gaan?'],
    ['Lucía', '¡Vale! ¿Dónde quedamos?', 'Oké! Waar spreken we af?'],
    ['Tomás', 'Delante del cine, a las ocho.', 'Voor de bioscoop, om acht uur.'],
    ['Lucía', 'De acuerdo. ¡Hasta el sábado!', 'Afgesproken. Tot zaterdag!'],
  ]),
  dialoog('dlg-u2-invitacion', 2, 'Een uitnodiging', 'Carmen nodigt Javi uit; zaterdag kan hij niet, zondag wel.', [
    ['Carmen', 'Oye, Javi, ¿qué vas a hacer este fin de semana?', 'Zeg, Javi, wat ga je dit weekend doen?'],
    ['Javi', 'El sábado voy a estudiar. El lunes tengo un examen.', 'Zaterdag ga ik studeren. Maandag heb ik een examen.'],
    ['Carmen', '¡Qué pena! El sábado por la noche hay un concierto de jazz.', 'Wat jammer! Zaterdagavond is er een jazzconcert.'],
    ['Javi', 'Lo siento, pero no puedo. ¿Y el domingo?', 'Sorry, maar ik kan niet. En zondag?'],
    ['Carmen', 'El domingo quiero dar un paseo por el parque. ¿Vienes conmigo?', 'Zondag wil ik een wandeling maken in het park. Ga je mee?'],
    ['Javi', 'Sí, con mucho gusto. ¿A qué hora quedamos?', 'Ja, heel graag. Hoe laat spreken we af?'],
    ['Carmen', '¿A las once? Paso por tu casa.', 'Om elf uur? Ik kom bij je langs.'],
    ['Javi', 'Perfecto. Después podemos tomar algo en un bar.', 'Perfect. Daarna kunnen we iets drinken in een café.'],
    ['Carmen', '¡Buena idea! Hasta el domingo.', 'Goed idee! Tot zondag.'],
  ]),
  dialoog('dlg-u2-pedir', 2, 'Bestellen in het restaurant', 'Ana en Luis bestellen hun avondeten bij de ober.', [
    ['Camarero', 'Buenas noches. ¿Qué van a tomar de primero?', 'Goedenavond. Wat nemen jullie als voorgerecht?'],
    ['Ana', 'Para mí, una ensalada mixta, por favor.', 'Voor mij een gemengde salade, alstublieft.'],
    ['Camarero', '¿Y para usted, señor?', 'En voor u, meneer?'],
    ['Luis', 'Yo quiero el gazpacho.', 'Ik wil de gazpacho.'],
    ['Camarero', 'Muy bien. ¿Y de segundo?', 'Heel goed. En als hoofdgerecht?'],
    ['Ana', '¿Qué nos recomienda?', 'Wat raadt u ons aan?'],
    ['Camarero', 'La paella de la casa está riquísima.', 'De paella van het huis is heerlijk.'],
    ['Luis', 'Pues paella para los dos.', 'Doe dan maar paella voor ons tweeën.'],
    ['Camarero', '¿Y para beber?', 'En om te drinken?'],
    ['Ana', 'Una botella de agua y dos copas de vino tinto.', 'Een fles water en twee glazen rode wijn.'],
    ['Camarero', 'Muy bien, ahora mismo.', 'Heel goed, komt eraan.'],
  ]),
  dialoog('dlg-u2-cuenta', 2, 'De rekening, alstublieft', 'Na het eten vragen Ana en Luis de rekening en betalen ze.', [
    ['Luis', 'Perdone, ¿nos trae la cuenta, por favor?', 'Pardon, mogen we de rekening, alstublieft?'],
    ['Camarero', 'Sí, claro. ¿No van a tomar postre o café?', 'Ja, natuurlijk. Nemen jullie geen dessert of koffie?'],
    ['Luis', 'Un café solo para mí, gracias.', 'Een zwarte koffie voor mij, dank u.'],
    ['Ana', 'Y para mí, un cortado.', 'En voor mij een koffie met een wolkje melk.'],
    ['Camarero', 'Aquí tienen los cafés y la cuenta. Son cuarenta y seis euros.', 'Alstublieft, de koffie en de rekening. Dat is zesenveertig euro.'],
    ['Luis', '¿Se puede pagar con tarjeta?', 'Kan ik met de kaart betalen?'],
    ['Camarero', 'Sí, por supuesto.', 'Ja, natuurlijk.'],
    ['Ana', 'Luis, ¿dejamos propina?', 'Luis, laten we een fooi achter?'],
    ['Luis', 'Sí, claro. El camarero es muy amable.', 'Ja, zeker. De ober is heel vriendelijk.'],
    ['Camarero', 'Muchas gracias. ¡Hasta pronto!', 'Hartelijk dank. Tot ziens!'],
  ]),

  /* ---- Unidad 3: Casa nueva, vida nueva (woning, meubels, indefinido) ---- */
  dialoog('dlg-u3-piso', 3, 'Een appartement bezoeken', 'Daniel bezoekt een appartement dat hij wil huren; de eigenares leidt hem rond.', [
    ['Propietaria', 'Pase, pase. Este es el salón comedor.', 'Kom binnen, kom binnen. Dit is de woonkamer met eethoek.'],
    ['Daniel', '¡Qué grande! Y tiene mucha luz.', 'Wat groot! En er is veel licht.'],
    ['Propietaria', 'Sí, tiene dos ventanas grandes. La cocina está a la izquierda.', 'Ja, er zijn twee grote ramen. De keuken is links.'],
    ['Daniel', '¿El piso está amueblado?', 'Is het appartement gemeubileerd?'],
    ['Propietaria', 'Sí, hay un sofá, una mesa y sillas. En la cocina hay nevera.', 'Ja, er zijn een bank, een tafel en stoelen. In de keuken staat een koelkast.'],
    ['Daniel', '¿Y cuántos dormitorios tiene?', 'En hoeveel slaapkamers zijn er?'],
    ['Propietaria', 'Tiene dos dormitorios y un baño.', 'Er zijn twee slaapkamers en een badkamer.'],
    ['Daniel', '¿En qué planta está? ¿Hay ascensor?', 'Op welke verdieping is het? Is er een lift?'],
    ['Propietaria', 'Está en el tercero, y sí, hay ascensor.', 'Op de derde, en ja, er is een lift.'],
    ['Daniel', '¿Cuánto cuesta el alquiler al mes?', 'Hoeveel is de huur per maand?'],
    ['Propietaria', 'Setecientos euros, con el agua incluida.', 'Zevenhonderd euro, water inbegrepen.'],
    ['Daniel', 'Me gusta mucho. ¿Puedo pensarlo hasta mañana?', 'Ik vind het heel mooi. Mag ik er tot morgen over nadenken?'],
  ]),
  dialoog('dlg-u3-mudanza', 3, 'Waar zet ik dit?', 'Iker helpt Marta verhuizen en vraagt waar alles moet komen.', [
    ['Iker', 'Marta, ¿dónde pongo esta caja?', 'Marta, waar zet ik deze doos?'],
    ['Marta', 'Cuidado, es frágil. Encima de la mesa, por favor.', 'Voorzichtig, hij is breekbaar. Op de tafel, alsjeblieft.'],
    ['Iker', 'Vale. ¿Y la lámpara?', 'Oké. En de lamp?'],
    ['Marta', 'Al lado del sofá, delante de la ventana.', 'Naast de bank, voor het raam.'],
    ['Iker', '¿Y el espejo? ¿Dónde lo pongo?', 'En de spiegel? Waar zet ik die?'],
    ['Marta', 'En el dormitorio, al lado del armario.', 'In de slaapkamer, naast de kast.'],
    ['Iker', '¿Y todos estos libros? Hay muchísimos.', 'En al die boeken? Het zijn er heel veel.'],
    ['Marta', 'En la estantería del pasillo.', 'In het boekenrek in de gang.'],
    ['Iker', '¡Uf! Estoy muy cansado.', 'Oef! Ik ben heel moe.'],
    ['Marta', 'Venga, primero vamos a tomar un café.', 'Kom, eerst gaan we een koffie drinken.'],
  ]),
  dialoog('dlg-u3-finde', 3, 'Wat deed je in het weekend?', 'Op maandag vertellen Elena en Pedro elkaar wat ze in het weekend gedaan hebben.', [
    ['Elena', 'Hola, Pedro. ¿Qué tal el fin de semana?', 'Hallo, Pedro. Hoe was je weekend?'],
    ['Pedro', 'Muy cansado. ¡El sábado me mudé de casa!', 'Heel vermoeiend. Zaterdag ben ik verhuisd!'],
    ['Elena', '¿De verdad? ¿Y quién te ayudó?', 'Echt? En wie heeft je geholpen?'],
    ['Pedro', 'Mis hermanos. Alquilamos un camión y trabajamos todo el día.', 'Mijn broers. We huurden een verhuiswagen en werkten de hele dag.'],
    ['Elena', '¿Y el domingo descansaste?', 'En heb je zondag uitgerust?'],
    ['Pedro', 'No mucho. Por la mañana compré una estantería nueva.', 'Niet veel. ’s Ochtends kocht ik een nieuw boekenrek.'],
    ['Elena', '¿Y por la tarde?', 'En ’s middags?'],
    ['Pedro', 'Fui al cine con Laura. ¿Y tú, qué hiciste?', 'Ik ging met Laura naar de film. En jij, wat heb jij gedaan?'],
    ['Elena', 'Me quedé en casa. Leí un libro y vi una serie.', 'Ik bleef thuis. Ik las een boek en keek naar een serie.'],
    ['Pedro', '¡Qué suerte! Un fin de semana muy tranquilo.', 'Wat een geluk! Een heel rustig weekend.'],
  ]),

  /* ---- Unidad 5: El gusto de aprender (leren, perfecto en indefinido) ---- */
  dialoog('dlg-u5-curso', 5, 'Inschrijven voor een cursus', 'Kris schrijft zich in aan een talenschool in Spanje.', [
    ['Secretaria', 'Buenos días. ¿En qué puedo ayudarle?', 'Goedendag. Waarmee kan ik u helpen?'],
    ['Kris', 'Quiero inscribirme en un curso de español.', 'Ik wil me inschrijven voor een cursus Spaans.'],
    ['Secretaria', 'Muy bien. ¿Ha estudiado español antes?', 'Heel goed. Hebt u al eerder Spaans gestudeerd?'],
    ['Kris', 'Sí, lo estudio desde hace un año en Bélgica.', 'Ja, ik studeer het al een jaar in België.'],
    ['Secretaria', 'Entonces el nivel A2 es para usted. Hay clases de mañana y de tarde.', 'Dan is niveau A2 iets voor u. Er zijn lessen ’s ochtends en ’s middags.'],
    ['Kris', 'Prefiero por la tarde. ¿Qué días son?', 'Ik heb liever ’s middags. Op welke dagen is dat?'],
    ['Secretaria', 'Los martes y los jueves, de seis a ocho.', 'Op dinsdag en donderdag, van zes tot acht.'],
    ['Kris', 'Perfecto. ¿Cuánto cuesta el curso?', 'Perfect. Hoeveel kost de cursus?'],
    ['Secretaria', 'Doscientos euros al mes, con el libro incluido.', 'Tweehonderd euro per maand, het boek inbegrepen.'],
    ['Kris', 'De acuerdo. ¿Qué necesito para la inscripción?', 'Akkoord. Wat heb ik nodig om me in te schrijven?'],
    ['Secretaria', 'Solo su nombre, su correo electrónico y su teléfono.', 'Alleen uw naam, uw e-mailadres en uw telefoonnummer.'],
  ]),
  dialoog('dlg-u5-hoy', 5, 'Wat heb je vandaag gedaan?', 'Leo komt thuis van school en vertelt zijn moeder over zijn dag.', [
    ['Madre', 'Hola, cariño. ¿Qué tal el día?', 'Hallo, schat. Hoe was je dag?'],
    ['Leo', 'Bien. Esta mañana hemos tenido un examen de inglés.', 'Goed. Vanochtend hadden we een examen Engels.'],
    ['Madre', '¿Y qué tal te ha salido?', 'En hoe is het gegaan?'],
    ['Leo', 'Creo que bien. He estudiado mucho esta semana.', 'Goed, denk ik. Ik heb deze week veel gestudeerd.'],
    ['Madre', '¿Has comido en el instituto?', 'Heb je op school gegeten?'],
    ['Leo', 'Sí, y después he jugado al fútbol con Hugo.', 'Ja, en daarna heb ik met Hugo gevoetbald.'],
    ['Madre', '¿Ya has hecho los deberes?', 'Heb je je huiswerk al gemaakt?'],
    ['Leo', 'Todavía no. Voy a hacerlos ahora.', 'Nog niet. Ik ga het nu maken.'],
    ['Madre', 'Muy bien. Yo todavía no he preparado la cena.', 'Heel goed. Ik heb het avondeten nog niet klaargemaakt.'],
    ['Leo', 'Si quieres, te ayudo después.', 'Als je wilt, help ik je straks.'],
  ]),
  dialoog('dlg-u5-este-ano', 5, 'Vorig jaar en dit jaar', 'Nuria en Jan praten over wat ze vorig jaar en dit jaar gedaan hebben.', [
    ['Nuria', 'Jan, ¿has estado alguna vez en México?', 'Jan, ben je ooit in Mexico geweest?'],
    ['Jan', 'Sí, estuve allí el año pasado, en julio.', 'Ja, ik was er vorig jaar, in juli.'],
    ['Nuria', '¿Y qué tal?', 'En hoe was het?'],
    ['Jan', 'Genial. Aprendí mucho español en un mes.', 'Geweldig. Ik leerde veel Spaans in één maand.'],
    ['Nuria', '¿Y este año has viajado?', 'En ben je dit jaar op reis geweest?'],
    ['Jan', 'No, este año no he viajado nada. He trabajado mucho.', 'Nee, dit jaar ben ik helemaal niet op reis geweest. Ik heb veel gewerkt.'],
    ['Nuria', 'Pero has empezado un curso de guitarra, ¿no?', 'Maar je bent met een gitaarcursus begonnen, toch?'],
    ['Jan', 'Sí, empecé en enero. ¡Me cuesta mucho!', 'Ja, ik begon in januari. Ik vind het heel moeilijk!'],
    ['Nuria', '¡Ánimo! Al principio a mí también me costó mucho.', 'Hou vol! In het begin vond ik het ook heel moeilijk.'],
    ['Jan', '¿Y ahora tocas bien?', 'En speel je nu goed?'],
    ['Nuria', 'Bastante bien. Hay que practicar todos los días.', 'Vrij goed. Je moet elke dag oefenen.'],
  ]),

  /* ---- Unidad 6: Te lo compro (winkelen, voornaamwoorden, qué/cuál) ---- */
  dialoog('dlg-u6-mercado', 6, 'Op de markt', 'Een klant koopt groenten en fruit bij een marktkramer.', [
    ['Vendedor', '¡Buenos días! ¿Qué le pongo?', 'Goedemorgen! Wat mag het zijn?'],
    ['Clienta', 'Quería un kilo de tomates, por favor.', 'Ik had graag een kilo tomaten, alstublieft.'],
    ['Vendedor', '¿Estos? Son muy buenos para ensalada.', 'Deze? Die zijn heel lekker voor een salade.'],
    ['Clienta', 'Sí, esos. ¿Y a cuánto están las naranjas?', 'Ja, die. En hoeveel kosten de sinaasappelen?'],
    ['Vendedor', 'A dos euros el kilo.', 'Twee euro per kilo.'],
    ['Clienta', 'Pues póngame dos kilos.', 'Geeft u me dan maar twee kilo.'],
    ['Vendedor', 'Aquí tiene. ¿Algo más?', 'Alstublieft. Nog iets?'],
    ['Clienta', 'Sí, medio kilo de fresas. ¿Cuánto es todo?', 'Ja, een halve kilo aardbeien. Hoeveel is het samen?'],
    ['Vendedor', 'Son ocho euros con cincuenta.', 'Dat is acht euro vijftig.'],
    ['Clienta', 'Tome. Gracias y hasta el sábado.', 'Alstublieft. Bedankt en tot zaterdag.'],
  ]),
  dialoog('dlg-u6-regalo', 6, 'Een cadeau kopen', 'Irene zoekt in een sportwinkel een verjaardagscadeau voor haar broer.', [
    ['Dependiente', 'Hola, ¿te puedo ayudar?', 'Hallo, kan ik je helpen?'],
    ['Irene', 'Sí, busco un regalo para mi hermano. Mañana es su cumpleaños.', 'Ja, ik zoek een cadeau voor mijn broer. Morgen is hij jarig.'],
    ['Dependiente', '¿Qué le gusta?', 'Waar houdt hij van?'],
    ['Irene', 'Le encanta el deporte. Juega al tenis y corre mucho.', 'Hij is gek op sport. Hij tennist en loopt veel.'],
    ['Dependiente', 'Mira, tenemos estas camisetas deportivas. Están de oferta.', 'Kijk, we hebben deze sportshirts. Ze zijn in de aanbieding.'],
    ['Irene', '¿Cuál me recomiendas, la roja o la azul?', 'Welk raad je me aan, het rode of het blauwe?'],
    ['Dependiente', 'La azul. Es de mejor calidad.', 'Het blauwe. Dat is van betere kwaliteit.'],
    ['Irene', 'Vale, me la llevo. ¿Me la envuelves para regalo?', 'Oké, ik neem het. Wil je het als cadeau inpakken?'],
    ['Dependiente', 'Claro, ahora mismo te la envuelvo.', 'Natuurlijk, ik pak het meteen voor je in.'],
    ['Irene', '¿Y si no le queda bien?', 'En als het hem niet past?'],
    ['Dependiente', 'Se puede cambiar en quince días con el tique de compra.', 'Het kan binnen vijftien dagen geruild worden met het kassabonnetje.'],
  ]),
  dialoog('dlg-u6-devolver', 6, 'Iets terugbrengen', 'Een klant brengt een broek terug die te klein is.', [
    ['Cliente', 'Buenas tardes. Ayer compré estos pantalones, pero me quedan pequeños.', 'Goedemiddag. Gisteren kocht ik deze broek, maar hij is me te klein.'],
    ['Dependienta', '¿Quiere cambiarlos por otra talla?', 'Wilt u hem ruilen voor een andere maat?'],
    ['Cliente', 'Sí, ¿los tiene en una talla más grande?', 'Ja, hebt u hem een maat groter?'],
    ['Dependienta', 'Lo siento, en este color ya no nos quedan.', 'Het spijt me, in deze kleur hebben we er geen meer.'],
    ['Cliente', 'Vaya. Entonces prefiero devolverlos.', 'Jammer. Dan breng ik hem liever terug.'],
    ['Dependienta', 'De acuerdo. ¿Tiene el tique de compra?', 'Goed. Hebt u het kassabonnetje?'],
    ['Cliente', 'Sí, aquí lo tiene.', 'Ja, alstublieft.'],
    ['Dependienta', '¿Pagó con tarjeta o en efectivo?', 'Hebt u met de kaart of contant betaald?'],
    ['Cliente', 'Con tarjeta.', 'Met de kaart.'],
    ['Dependienta', 'Muy bien, le devolvemos el dinero en la misma tarjeta.', 'Heel goed, we storten het geld terug op dezelfde kaart.'],
  ]),

  /* ---- Unidad 7: ¡Qué descanso! (lichaam, gezondheid, imperfecto) ---- */
  dialoog('dlg-u7-medico', 7, 'Bij de dokter', 'Een patiënt met keelpijn gaat op consultatie bij de dokter.', [
    ['Médica', 'Buenos días. ¿Qué le pasa?', 'Goedendag. Wat scheelt er?'],
    ['Paciente', 'Me duele mucho la garganta y tengo tos.', 'Ik heb erge keelpijn en ik hoest.'],
    ['Médica', '¿Desde cuándo está así?', 'Sinds wanneer hebt u dat?'],
    ['Paciente', 'Desde hace tres días. Y esta noche he tenido fiebre.', 'Al drie dagen. En vannacht had ik koorts.'],
    ['Médica', 'A ver… Abra la boca, por favor.', 'Eens kijken… Doe uw mond open, alstublieft.'],
    ['Paciente', '¿Es algo grave?', 'Is het iets ernstigs?'],
    ['Médica', 'No, es un resfriado fuerte. Tiene que descansar y beber mucha agua.', 'Nee, het is een zware verkoudheid. U moet rusten en veel water drinken.'],
    ['Paciente', '¿Necesito algún medicamento?', 'Heb ik een medicijn nodig?'],
    ['Médica', 'Sí, tome este jarabe tres veces al día.', 'Ja, neem deze siroop drie keer per dag.'],
    ['Paciente', 'Muchas gracias, doctora.', 'Hartelijk dank, dokter.'],
  ]),
  dialoog('dlg-u7-farmacia', 7, 'In de apotheek', 'Een vrouw met hoofdpijn vraagt de apotheker om raad.', [
    ['Farmacéutico', 'Hola, buenas tardes.', 'Hallo, goedemiddag.'],
    ['Clienta', 'Hola. ¿Tiene algo para el dolor de cabeza?', 'Hallo. Hebt u iets tegen hoofdpijn?'],
    ['Farmacéutico', 'Sí, estas pastillas son muy buenas. ¿Le duele mucho?', 'Ja, deze pillen zijn heel goed. Doet het erg pijn?'],
    ['Clienta', 'Bastante. Además estoy muy cansada y me duele la espalda.', 'Behoorlijk. Bovendien ben ik heel moe en heb ik rugpijn.'],
    ['Farmacéutico', '¿Tiene fiebre?', 'Hebt u koorts?'],
    ['Clienta', 'Creo que no. Anoche trabajé hasta muy tarde.', 'Ik denk het niet. Gisteravond heb ik tot heel laat gewerkt.'],
    ['Farmacéutico', 'Entonces tome una pastilla cada ocho horas y descanse.', 'Neem dan om de acht uur een pil en rust uit.'],
    ['Clienta', '¿Las puedo tomar con el estómago vacío?', 'Mag ik ze op een lege maag innemen?'],
    ['Farmacéutico', 'Mejor no. Tómelas después de comer.', 'Liever niet. Neem ze na het eten.'],
    ['Clienta', 'Muy bien. ¿Cuánto es?', 'Heel goed. Hoeveel is het?'],
    ['Farmacéutico', 'Son cuatro euros con veinte.', 'Dat is vier euro twintig.'],
  ]),
  dialoog('dlg-u7-infancia', 7, 'Vakanties van vroeger', 'Marina en Alex vertellen hoe hun zomervakanties waren toen ze klein waren.', [
    ['Alex', 'Marina, ¿adónde ibas de vacaciones cuando eras pequeña?', 'Marina, waar ging jij op vakantie toen je klein was?'],
    ['Marina', 'Siempre íbamos a la playa, a casa de mis abuelos.', 'We gingen altijd naar zee, naar het huis van mijn grootouders.'],
    ['Alex', '¡Qué bien! ¿Y qué hacíais allí?', 'Wat leuk! En wat deden jullie daar?'],
    ['Marina', 'Nadábamos todos los días y por la tarde comíamos helado.', 'We zwommen elke dag en ’s middags aten we ijs.'],
    ['Alex', 'Nosotros no íbamos nunca a la playa.', 'Wij gingen nooit naar zee.'],
    ['Marina', '¿No? ¿Y dónde pasabais el verano?', 'Nee? En waar brachten jullie de zomer door?'],
    ['Alex', 'En el campo. Mis padres tenían una casa pequeña en un pueblo.', 'Op het platteland. Mijn ouders hadden een klein huis in een dorp.'],
    ['Marina', '¿Y te gustaba?', 'En vond je dat leuk?'],
    ['Alex', 'Sí, mucho. Jugaba con mis primos y montábamos en bici.', 'Ja, heel erg. Ik speelde met mijn neven en we fietsten.'],
    ['Marina', '¡Qué descanso! Ahora mis vacaciones son mucho más cortas.', 'Wat een rust! Nu zijn mijn vakanties veel korter.'],
  ]),
];

export default {
  atoms: DIALOGEN.flatMap(d => d.atoms),
  texts: Object.assign({}, ...DIALOGEN.map(d => d.text)),
};
