/* Ezelsbruggetjes bij de woordenschat.
 *
 * Verschijnt onder een fout antwoord (en achter op een flashcard): één korte
 * haak om het woord aan op te hangen. Bij voorkeur een verwant woord dat je
 * al kent — Frans, Engels, Latijn, Nederlands — of een herkomst die het woord
 * doorzichtig maakt (desayunar = des + ayunar, het vasten breken). Een gezocht
 * rijmpje helpt niet; dan liever niets.
 *
 * Regels die voor een hele groep woorden gelden (woorden op -ción zijn
 * vrouwelijk, -dor is een toestel, es- voor s + medeklinker …) staan hier niet:
 * die berekent js/hints.js zelf. Wat hier staat is per woord.
 *
 * `regroup.mjs` zet de tekst als `memo` op het atoom; een onbekende id is een
 * aandachtspunt, zodat een hernoemd woord zijn ezelsbrug niet stil verliest.
 */

const DAYS = 'De weekdagen zijn naar de planeten genoemd, net als in het Frans: ';
const THREE_PLACES = 'aquí (hier, bij mij) · ahí (daar, bij jou) · allí (ginder, ver weg) — zoals este, ese, aquel.';
const N_WORDS = 'De ontkenningen beginnen met n-: nada, nadie, nunca, ninguno — tegenover algo, alguien, siempre, alguno.';
const WEATHER = 'Bij het weer gebruik je hacer: hace calor, hace frío, hace sol, hace viento (het "maakt" warm).';
const TEENS = '11 tot 15 eindigen op -ce, zoals in het Frans (onze, douze, treize, quatorze, quinze). Vanaf 16: dieci- + getal.';
const TENS = '-enta is ons -tig: cuarenta, cincuenta, sesenta … Alleen 20 (veinte) en 30 (treinta) wijken af.';
const ARABIC = 'Begint met al- of a-: veel zulke woorden komen uit het Arabisch, waar al- het lidwoord is.';
const F_TO_H = 'Waar het Latijn een f had, schrijft het Spaans vaak een h: ';
const COMPOUND = 'Zo\'n samenstelling van werkwoord + zelfstandig naamwoord is mannelijk en verandert niet in het meervoud (el / los paraguas).';

export const MEMO = {
  /* --- kleding en accessoires --- */
  'v.el-algodon': 'Uit het Arabisch al-qutun; vgl. Engels cotton, Frans coton.',
  'v.el-boton': 'Vgl. Engels button, Frans bouton.',
  'v.el-cinturon': 'Vgl. ceintuur (Frans ceinture).',
  'v.el-cuero': 'Vgl. Frans cuir.',
  'v.el-guante': 'Vgl. Frans gant.',
  'v.el-panuelo': 'Van el paño = de doek: een klein doekje.',
  'v.el-paraguas': 'para + aguas: "houdt het water tegen", zoals een parasol de zon. ' + COMPOUND,
  'v.el-sombrero': 'Van la sombra = de schaduw: de hoed geeft schaduw.',
  'v.el-reloj': 'Uit Latijn horologium — dezelfde stam als horloge.',
  'v.la-bota': 'Vgl. Engels boot, Frans botte.',
  'v.la-cartera': 'Van la carta = de brief, het papier: daar steek je je papieren in.',
  'v.la-corbata': 'De das dankt zijn naam aan de Kroatische ruiters; vgl. Frans cravate.',
  'v.la-lana': 'Vgl. lanoline, het vet uit schapenwol.',
  'v.el-abrigo': 'abrigar = beschutten; vgl. Frans abri (schuilplaats).',
  'v.el-banador': 'Van bañarse = zwemmen, baden.',
  'v.el-probador': 'Van probar = passen: de kamer waar je kleren probeert.',
  'v.el-vestido': 'Van vestir = (aan)kleden. Geen vest, maar een jurk.',
  'v.la-camisa': 'Vgl. Frans chemise.',
  'v.la-camiseta': 'camisa + -eta (verkleinwoord): het "hemdje".',
  'v.la-chaqueta': 'Vgl. Engels jacket, Frans jaquette.',
  'v.la-falda': 'Vgl. Engels fold: een rok valt in plooien.',
  'v.la-ropa': 'Vgl. Engels robe en garderobe.',
  'v.los-pantalones': 'Vgl. pantalon, Engels pants.',
  'v.los-vaqueros': 'el vaquero = de cowboy (van la vaca = de koe): de broek van de cowboys.',
  'v.los-tejanos': 'tejano = uit Texas: de broek van de cowboys.',
  'v.los-calcetines': 'Van la calza = de kous: calcetín is het korte kousje.',
  'v.las-medias': 'Ingekort uit medias calzas, "halve kousen".',
  'v.los-zapatos': 'Vgl. Frans sabot (klomp).',
  'v.las-botas': 'Vgl. Engels boots, Frans bottes.',
  'v.las-sandalias': 'Vgl. sandalen.',
  'v.el-chandal': 'Uit het Frans chandail, de trui van de marchand d\'ail (knoflookverkoper) op de markt.',
  'v.el-jersey': 'Naar het eiland Jersey, bekend om zijn wollen truien.',
  'v.el-sosten': 'Van sostener = ondersteunen.',
  'v.el-sujetador': 'Van sujetar = vasthouden.',
  'v.la-cazadora': 'Van cazar = jagen: het jasje van de jager.',
  'v.la-chaqueta-impermeable': 'impermeable = waterdicht (vgl. permeabel = doorlatend).',
  'v.el-anillo': 'Vgl. Latijn anulus (ringetje), en annulair = ringvormig.',
  'v.las-joyas': 'Vgl. Engels jewel, Frans joyau.',

  /* --- huis en toestellen --- */
  'v.el-horno': F_TO_H + 'Latijn furnus → horno (vgl. fornuis, Frans four).',
  'v.el-interruptor': 'Van interrumpir = onderbreken: de schakelaar onderbreekt de stroom.',
  'v.el-lavaplatos': 'lava + platos: "wast de borden". ' + COMPOUND,
  'v.el-lavavajillas': 'lava + vajillas: "wast de vaat". ' + COMPOUND,
  'v.el-microondas': 'micro + ondas (golven): de microgolfoven.',
  'v.el-televisor': 'el televisor = het toestel, la televisión = de televisie als medium.',
  'v.la-nevera': 'Van la nieve = de sneeuw: de "sneeuwkast".',
  'v.la-plancha': 'la plancha = de platte plaat: het strijkijzer, en a la plancha = op de bakplaat.',
  'v.el-fregadero': 'Van fregar = afwassen, schrobben: de plek waar je afwast.',
  'v.el-inodoro': 'in + odoro: "zonder geur" (vgl. inodore).',
  'v.el-lavabo': 'Van lavar = wassen — net als onze lavabo.',
  'v.la-banera': 'Van bañarse = baden.',
  'v.la-estufa': 'Vgl. Engels stove en ons stoof.',
  'v.el-ascensor': 'Van ascender = stijgen (Frans ascenseur).',
  'v.el-aseo': 'Van asearse = zich opfrissen.',
  'v.el-atico': 'Vgl. Engels attic.',
  'v.el-dormitorio': 'Van dormir = slapen (Engels dormitory).',
  'v.el-edificio': 'Vgl. Engels edifice.',
  'v.el-pasillo': 'Verkleinwoord van el paso = de doorgang.',
  'v.el-sotano': 'Uit Latijn subtus = onder.',
  'v.el-techo': 'Latijn tectum = dak (vgl. Engels protect: afdekken). Betekent ook plafond.',
  'v.la-calefaccion': 'Van calor (warmte) + hacer: "warmte maken".',
  'v.la-escalera': 'Vgl. escaleren en Engels escalator: trap op.',
  'v.la-habitacion': 'Van habitar = wonen (Engels inhabit).',
  'v.la-pared': 'la pared = de (binnen)muur; el muro = de buitenmuur.',
  'v.el-muro': 'el muro = de buitenmuur; la pared = de wand binnen.',
  'v.la-puerta': 'Vgl. portier, portaal en Frans porte.',
  'v.la-salida': 'Van salir = buitengaan.',
  'v.la-entrada': 'Van entrar = binnengaan.',
  'v.la-ventana': 'Van el viento = de wind: het raam laat de wind binnen (vgl. ventileren).',
  'v.la-vivienda': 'Van vivir = wonen.',
  'v.el-cuadro': 'Van cuadrado = vierkant: wat in een kader hangt.',
  'v.el-espejo': 'Uit Latijn speculum, net als ons spiegel.',
  'v.la-alfombra': ARABIC,
  'v.la-bombilla': 'Verkleinwoord van la bomba: een "bommetje" van glas.',
  'v.la-luz': 'Vgl. lux en lucide. Meervoud: las luces (z wordt c).',
  'v.el-armario': 'Vgl. Frans armoire: oorspronkelijk een wapenkast (el arma = het wapen).',
  'v.el-escritorio': 'Van escribir = schrijven: de schrijftafel.',
  'v.el-sillon': 'la silla + -ón (vergroting): de "grote stoel".',
  'v.el-taburete': 'Vgl. Frans tabouret.',
  'v.la-mesa': 'Ezelsbrug: op de mesa ligt het mes.',
  'v.la-estanteria': 'Van el estante = de plank.',
  'v.los-muebles': 'Vgl. Frans meubles: wat je kan verplaatsen (Engels mobile).',
  'v.el-cubo-de-basura': 'el cubo = de emmer, la basura = het afval.',

  /* --- eten en drinken --- */
  'v.a-la-brasa': 'la brasa = de gloeiende houtskool (vgl. Frans braise).',
  'v.asado': 'Van asar = braden, roosteren.',
  'v.el-asado': 'Van asar = braden, roosteren.',
  'v.empanado': 'Van el pan: "in brood(kruim)" = gepaneerd.',
  'v.la-empanada': 'Van el pan: deeg met een vulling, "ingebrood".',
  'v.el-batido': 'Van batir = kloppen, mixen.',
  'v.el-cafe-solo': 'solo = alleen: koffie zonder iets erbij.',
  'v.el-cortado': 'Van cortar = snijden: de koffie wordt "gesneden" met een scheutje melk.',
  'v.el-vino-tinto': 'tinto = gekleurd (vgl. tint). Rode wijn is nooit vino rojo.',
  'v.la-cana': 'la caña = het riet, de buis: een smal glas.',
  'v.la-leche-desnatada': 'la nata = de room; des-natada = ontroomd.',
  'v.la-leche-semidesnatada': 'la nata = de room; semi-desnatada = half ontroomd.',
  'v.la-leche-entera': 'entero = heel, volledig (Engels entire).',
  'v.el-albaricoque': ARABIC + ' Vgl. Frans abricot.',
  'v.el-higo': F_TO_H + 'Latijn ficus → higo (Engels fig).',
  'v.el-melocoton': 'Ezelsbrug: melo + cotón (katoen): de vrucht met het donzige vel.',
  'v.el-platano': 'Vgl. Engels plantain (bakbanaan).',
  'v.la-cereza': 'Vgl. Engels cherry, Frans cerise.',
  'v.la-frambuesa': 'Vgl. Frans framboise.',
  'v.la-fresa': 'Vgl. Frans fraise.',
  'v.la-granada': 'Granaatappel en handgranaat delen hun naam; de stad Granada heeft er een in het wapen.',
  'v.la-manzana': 'Ezelsbrug: Adam was de eerste man die een manzana at.',
  'v.la-naranja': 'Zelfde Perzisch-Arabische stam als Engels orange; naranja is ook de kleur oranje.',
  'v.la-pina': 'la piña = de dennenappel: de ananas lijkt erop (Engels pineapple).',
  'v.el-ciervo': 'Vgl. Frans cerf.',
  'v.el-conejo': 'Uit Latijn cuniculus, net als ons konijn.',
  'v.el-jabali': 'Arabisch jabalī, "van de berg": het wilde bergzwijn.',
  'v.el-pavo': 'Latijn pavo = pauw.',
  'v.el-pollo': 'Vgl. Frans poule, Engels poultry.',
  'v.la-liebre': 'Vgl. Frans lièvre.',
  'v.la-pechuga-de-pollo': 'Van el pecho = de borst.',
  'v.el-aguacate': 'Uit het Azteekse ahuacatl, waar ook avocado van komt.',
  'v.el-calabacin': 'Verkleinwoord van la calabaza (pompoen): de courgette.',
  'v.la-calabaza': 'Vgl. Engels calabash, ons kalebas.',
  'v.el-esparrago': 'Vgl. Engels asparagus.',
  'v.el-pepinillo': 'Verkleinwoord van el pepino (komkommer): het "komkommertje".',
  'v.el-pimiento': 'el pimiento = de paprika (groente), la pimienta = de peper (kruid).',
  'v.la-pimienta': 'la pimienta = de peper (kruid), el pimiento = de paprika (groente).',
  'v.el-pimenton': 'Van el pimiento (paprika) + -ón: het paprikapoeder.',
  'v.el-puerro': 'Vgl. Frans poireau.',
  'v.la-aceituna': ARABIC + ' Familie van el aceite = de olie.',
  'v.la-alcachofa': ARABIC + ' Vgl. Engels artichoke.',
  'v.la-berenjena': 'Uit het Arabisch bādhinjān, net als Frans aubergine.',
  'v.la-cebolla': 'Uit Latijn cepulla, net als Duits Zwiebel.',
  'v.el-cebollino': 'Verkleinwoord van la cebolla: het "uitje" = bieslook.',
  'v.la-col': 'Vgl. ons kool en Engels coleslaw.',
  'v.la-coliflor': 'col + flor: "koolbloem" — bloemkool omgedraaid. Vrouwelijk, zoals la flor.',
  'v.la-lechuga': 'Van la leche = de melk: sla heeft een melkachtig sap.',
  'v.las-coles-de-bruselas': 'Letterlijk "kolen van Brussel".',
  'v.el-azafran': ARABIC + ' Vgl. Engels saffron.',
  'v.el-jengibre': 'Vgl. Engels ginger.',
  'v.el-tomillo': 'Vgl. Engels thyme, Frans thym.',
  'v.la-albahaca': ARABIC,
  'v.la-canela': 'Van la caña (riet, buis): kaneel zit in opgerolde stokjes.',
  'v.la-mostaza': 'Vgl. Engels mustard, Frans moutarde.',
  'v.la-sal': 'Vgl. Frans sel. Vrouwelijk, al eindigt het op een medeklinker: la sal.',
  'v.el-queso': 'Uit Latijn caseus, net als kaas en Engels cheese.',
  'v.el-queso-curado': 'curar = ook laten rijpen: curado = gerijpt, belegen.',
  'v.el-cacahuete': 'Uit het Azteekse tlālcacahuatl, "aardcacao".',
  'v.la-almendra': 'Vgl. Engels almond, Frans amande.',
  'v.la-castana': 'Vgl. kastanje; castaño = kastanjebruin (haar).',
  'v.la-alubia': ARABIC,
  'v.las-lentejas': 'Vgl. Frans lentilles: de lens heet zo omdat ze op een linze lijkt.',
  'v.el-atun': 'Uit het Arabisch at-tūn; vgl. Engels tuna.',
  'v.el-bacalao': 'Familie van ons kabeljauw (vroeger ook bakeljauw).',
  'v.el-lenguado': 'Van la lengua = de tong — net als in het Nederlands.',
  'v.el-pez-espada': 'la espada = het zwaard.',
  'v.la-anguila': 'Vgl. Frans anguille.',
  'v.la-dorada': 'dorado = goudkleurig: de goudbrasem.',
  'v.la-trucha': 'Vgl. Engels trout, Frans truite.',
  'v.el-cochinillo': 'el cochino = het varken, -illo = klein: het speenvarken.',
  'v.el-estofado': 'Vgl. stoven en Engels stew.',
  'v.la-albondiga': ARABIC + ' (al-bunduqa, het balletje)',
  'v.la-carne-picada': 'Van picar = fijnhakken.',
  'v.la-costilla': 'Vgl. Frans côte (rib) en côtelette.',
  'v.la-parrillada': 'la parrilla = de grill.',
  'v.la-salchicha': 'Van la sal: gezouten vlees (Engels sausage).',
  'v.los-embutidos': 'Van embutir = (op)stoppen: vlees dat in een darm gestopt is.',
  'v.el-cangrejo': 'Latijn cancer = krab (het sterrenbeeld Kreeft).',
  'v.el-langostino': 'Klein broertje van la langosta: de grote garnaal.',
  'v.el-pulpo': 'Uit het Grieks polypous, "veelvoet".',
  'v.la-ostra': 'Vgl. Engels oyster, Frans huître.',
  'v.la-sepia': 'Vgl. sepia, de bruine inkt van de zeekat.',
  'v.el-calamar': 'Vgl. calamares, Italiaans calamari.',
  'v.el-bizcocho': 'bis + cocho: "twee keer gebakken", net als biscuit.',
  'v.el-bocadillo': 'la boca → el bocado (een hap) → el bocadillo: een hapje.',
  'v.el-helado': 'Van helar = bevriezen; el hielo = het ijs(blokje).',
  'v.el-pastel': 'Vgl. pastei en pâtisserie.',
  'v.el-polvoron': 'Van el polvo = het poeder: het koekje verkruimelt in je mond.',
  'v.la-galleta': 'Vgl. Frans galette.',
  'v.la-mantequilla': 'Van la manteca = het vet: het "vetje" op je boterham.',
  'v.la-tostada': 'Van tostar = roosteren (Engels toast).',
  'v.las-palomitas': 'la paloma = de duif: popcorn lijkt op witte duifjes.',
  'v.el-cruasan': 'Het Franse croissant, op zijn Spaans gespeld.',

  /* --- gezondheid en lichaam --- */
  'v.contagioso-a': 'Vgl. Engels contagious.',
  'v.curar': 'Vgl. kuur, Engels cure.',
  'v.doler': 'el dolor = de pijn. me duele werkt als me gusta: wat pijn doet is het onderwerp.',
  'v.el-mareo': 'Van el mar = de zee: misselijk zoals bij zeeziekte.',
  'v.marearse': 'Van el mar = de zee: zeeziek worden.',
  'v.enfermo-a': 'Vgl. Engels infirm en infirmerie (ziekenboeg).',
  'v.la-enfermedad': 'Van enfermo = ziek (vgl. infirmerie).',
  'v.la-pastilla': 'Vgl. pastille.',
  'v.la-quemadura-de-sol': 'Van quemar = branden.',
  'v.la-quemadura': 'Van quemar = branden.',
  'v.la-tirita': 'Van la tira = de strook: een strookje.',
  'v.la-vacuna': 'Van la vaca: het eerste vaccin kwam van de koepokken.',
  'v.resfriado-a': 're + frío: je hebt kou gevat.',
  'v.el-resfriado': 're + frío: de kou die je gevat hebt.',
  'v.romperse': 'Vgl. Frans rompre. Voltooid deelwoord: roto.',
  'v.sangrar': 'la sangre = het bloed (Frans sang).',
  'v.sano-a': 'Vgl. sanatorium.',
  'v.tratar': 'Vgl. Engels treat (behandelen).',
  'v.el-cardenal': 'Hetzelfde woord als kardinaal: denk aan de purperen kleur.',
  'v.el-catarro': 'Vgl. catarre (slijmvliesontsteking).',
  'v.el-estrenimiento': 'Valse vrienden: estreñido = geconstipeerd, constipado = verkouden.',
  'v.la-fiebre': 'Vgl. Engels fever, Frans fièvre.',
  'v.la-gripe': 'Vgl. Frans grippe.',
  'v.la-picadura': 'Van picar = steken, prikken.',
  'v.la-torcedura': 'Van torcer = verdraaien (vgl. torsie).',
  'v.las-agujetas': 'la aguja = de naald: spierpijn prikt als naaldjes.',
  'v.el-brazo': 'Vgl. Frans bras en bracelet (armband).',
  'v.el-cabello': 'Vgl. Frans cheveux. Iets formeler dan el pelo.',
  'v.el-cerebro': 'Vgl. Engels cerebral.',
  'v.el-corazon': 'Vgl. cordiaal en Frans cœur.',
  'v.el-cuello': 'Vgl. Frans cou; el collar (halsketting) komt ervan.',
  'v.el-dedo': 'Vgl. Engels digit, Frans doigt.',
  'v.el-diente': 'Vgl. dentist, Frans dent.',
  'v.el-estomago': 'Vgl. Engels stomach.',
  'v.el-higado': F_TO_H + 'Latijn ficatum → hígado.',
  'v.el-hombro': 'Vgl. humerus, het bot van je bovenarm.',
  'v.el-labio': 'Vgl. Engels labial.',
  'v.el-menton': 'Vgl. Frans menton.',
  'v.el-oido': 'Van oír = horen: het gehoor. De oorschelp is la oreja.',
  'v.el-ojo': 'Ezelsbrug: in ojo zie je twee o\'s — twee ogen met een neus ertussen.',
  'v.el-pecho': 'Vgl. pectoraal (borstspier).',
  'v.el-pie': 'Vgl. Frans pied en pedaal.',
  'v.el-pulmon': 'Vgl. pulmonaal, Frans poumon.',
  'v.el-rinon': 'Vgl. renaal, Frans rein.',
  'v.el-vientre': 'Vgl. Frans ventre.',
  'v.la-barba': 'Vgl. barbier.',
  'v.la-boca': 'Vgl. Frans bouche.',
  'v.la-cabeza': 'Uit Latijn caput (vgl. kapitein: het hoofd).',
  'v.la-espalda': 'Vgl. Frans épaule (schouder): in het Spaans schoof de betekenis naar de rug.',
  'v.la-garganta': 'Vgl. gorgelen, Engels gargle.',
  'v.la-lengua': 'Vgl. linguïst: tong én taal, net als Engels tongue.',
  'v.la-muela': 'Van moler = malen (vgl. molaar): de kies maalt.',
  'v.la-nariz': 'Vgl. Frans narine (neusgat). Meervoud: las narices.',
  'v.la-piel': 'Uit Latijn pellis, net als pels.',
  'v.la-rodilla': 'Uit Latijn rotella, "wieltje": de ronde knieschijf.',
  'v.la-sangre': 'Vgl. Frans sang.',
  'v.la-una': 'Vgl. Frans ongle. Let op de ñ: uña = nagel, una = een.',
  'v.la-mano': 'Vgl. manueel en manicure.',

  /* --- vrije tijd en sport --- */
  'v.bailar': 'Vgl. bal (dansfeest), Engels ball.',
  'v.cantar': 'Vgl. cantate, Engels chant.',
  'v.cocinar': 'la cocina = de keuken.',
  'v.coser': 'coser (met s) = naaien; cocer (met c) = koken.',
  'v.descansar': 'des + cansar: het moe zijn (cansado) wegnemen.',
  'v.escalar': 'la escala = de ladder (vgl. escaleren).',
  'v.leer': 'Vgl. lectuur, Frans lire.',
  'v.montar-a-caballo': 'el caballo = het paard (vgl. cavalerie, Frans cheval).',
  'v.pasear': 'el paseo = de wandeling.',
  'v.pescar': 'el pez = de vis (Frans pêcher).',
  'v.pintar': 'Vgl. Engels paint, Frans peindre.',
  'v.salir': 'la salida = de uitgang.',
  'v.el-deporte': 'Engels sport is ingekort uit disport, "ontspanning" — dezelfde stam.',
  'v.hacer-senderismo': 'el sendero = het wandelpad.',
  'v.patinar': 'Vgl. Frans patiner; los patines = de schaatsen.',
  'v.navegar': 'Vgl. navigeren.',
  'v.tocar': 'tocar = aanraken (Frans toucher): je raakt een instrument aan om het te bespelen.',
  'v.cenar': 'la cena = het avondmaal (la Última Cena = het Laatste Avondmaal).',
  'v.el-sello': 'Vgl. zegel: sellar = verzegelen.',
  'v.la-aficion': 'Vgl. aficionado (liefhebber).',
  'v.la-moneda': 'Vgl. Engels money en monetair.',
  'v.el-juego': 'Van jugar: dezelfde u → ue als in juego (ik speel).',
  'v.la-ficha': 'Vgl. fiche.',
  'v.avanzar': 'Vgl. Frans avancer.',

  /* --- dagelijks leven --- */
  'v.aburrir-se': 'Klinkt een beetje als boring: je verveelt je.',
  'v.cansarse': 'cansado = moe.',
  'v.despacio': 'Uit de espacio, "met ruimte": op je gemak.',
  'v.la-fila': 'Vgl. de file op de weg: een lange rij.',
  'v.la-vida-cotidiana': 'cotidiano = dagelijks (Frans quotidien).',
  'v.cotidiano-a': 'Vgl. Frans quotidien.',
  'v.olvidar': 'Vgl. Engels oblivion (vergetelheid).',
  'v.olvidar-se': 'Vgl. Engels oblivion (vergetelheid).',
  'v.tener-prisa': 'la prisa = de haast (vgl. Engels press: onder druk).',
  'v.el-otono': 'Vgl. Engels autumn, Frans automne.',
  'v.el-invierno': 'Vgl. Frans hiver, Italiaans inverno.',
  'v.la-primavera': 'Uit Latijn primo vere, "aan het begin van de lente".',
  'v.la-epoca': 'Vgl. Frans époque.',
  'v.lunes': DAYS + 'lunes = dag van de maan (la luna).',
  'v.martes': DAYS + 'martes = dag van Mars (Frans mardi).',
  'v.miercoles': DAYS + 'miércoles = dag van Mercurius (Frans mercredi).',
  'v.jueves': DAYS + 'jueves = dag van Jupiter (Frans jeudi).',
  'v.viernes': DAYS + 'viernes = dag van Venus (Frans vendredi).',
  'v.sabado': 'Van de sabbat, de rustdag.',
  'v.domingo': 'Van Latijn dominus = de Heer: de dag van de Heer.',
  'v.casarse': 'Van la casa: trouwen is samen een huis nemen.',
  'v.llamarse': 'llamar = roepen: ¿Cómo te llamas? is "hoe roep je jezelf?"',
  'v.peinarse': 'el peine = de kam.',
  'v.irse': 'ir = gaan, irse = weggaan: me voy = ik ben weg.',
  'v.divertirse': 'Vgl. divertissement.',
  'v.el-tiempo': 'Het weer én de tijd, net als Frans le temps.',
  'v.el-viento': 'Vgl. ventilator en ventiel.',
  'v.la-niebla': 'Uit Latijn nebula, net als nevel.',
  'v.llover': 'la lluvia = de regen.',
  'v.nevar': 'la nieve = de sneeuw (Sierra Nevada = het besneeuwde gebergte).',
  'v.hace-calor': WEATHER,
  'v.hace-frio': WEATHER,
  'v.hace-sol': WEATHER,
  'v.hace-viento': WEATHER,
  'v.hace-buen-tiempo': WEATHER,
  'v.hace-mal-tiempo': WEATHER,
  'v.hace-5-grados': WEATHER,
  'v.hay-niebla': 'Mist "is er": hay niebla. Zon en wind "maakt" het: hace sol, hace viento.',
  'v.esta-nublado': 'estar + bijvoeglijk naamwoord: está nublado, bewolkt is een toestand.',

  /* --- werkwoorden --- */
  'v.apuntar': 'la punta = de punt: met de punt van je pen opschrijven.',
  'v.caminar': 'el camino = de weg.',
  'v.charlar': 'Vgl. charlatan, die veel praat.',
  'v.desayunar': 'des + ayunar (vasten): het vasten breken — net als Engels breakfast.',
  'v.esperar': 'Wachten én hopen: la esperanza = de hoop.',
  'v.explicar': 'Vgl. Engels explain.',
  'v.fumar': 'Vgl. Frans fumer. Met een h: el humo = de rook.',
  'v.hablar': F_TO_H + 'Latijn fabulare (vgl. fabel) → hablar.',
  'v.mirar': 'Vgl. Engels mirror: waar je in kijkt.',
  'v.pagar': 'Vgl. Frans payer.',
  'v.preguntar': 'la pregunta = de vraag.',
  'v.trabajar': 'Vgl. Frans travailler.',
  'v.viajar': 'el viaje = de reis (Frans voyage).',
  'v.aprender': 'Vgl. Frans apprendre.',
  'v.beber': 'Vgl. Engels beverage, Frans boire.',
  'v.correr': 'Vgl. koerier (courier): die loopt snel.',
  'v.creer': 'Vgl. credo.',
  'v.deber': 'Vgl. debet: el deber = de plicht.',
  'v.prometer': 'Vgl. Engels promise.',
  'v.temer': 'el temor = de vrees (vgl. timide).',
  'v.vender': 'Vgl. venten, Frans vendre.',
  'v.partir': 'Vgl. Frans partir; ook: (ver)delen.',
  'v.recibir': 'Vgl. Engels receive.',
  'v.subir': 'subir = naar boven, bajar = naar beneden.',
  'v.vivir': 'Vgl. Frans vivre.',
  'v.cambiar': 'el cambio = de wissel, het wisselgeld.',
  'v.llevarse': 'llevar = dragen, llevarse = met je meedragen.',
  'v.recorrer': 're + correr: van begin tot eind afleggen.',
  'v.acostumbrarse-a': 'la costumbre = de gewoonte (Engels custom).',
  'v.convenir': 'Vgl. Engels convenient.',
  'v.disfrutar-de': 'des + fruto: de vruchten plukken van iets.',
  'v.durar': 'Vgl. duur en Engels during.',
  'v.senalar': 'la señal = het teken (Engels signal).',
  'v.encantar': 'Vgl. Engels enchanted: betoverd.',
  'v.rechazar': 'Vgl. Frans rechasser: terugjagen.',
  'v.la-propuesta': 'Van proponer = voorstellen (Engels propose).',
  'v.el-ordenador': 'Van ordenar = ordenen, net als Frans ordinateur.',

  /* --- kantoor --- */
  'v.el-boligrafo': 'bola + grafo: een balletje dat schrijft (vgl. grafiek).',
  'v.el-cuaderno': 'Uit Latijn quaterni (vier vellen), net als Frans cahier.',
  'v.el-lapiz': 'Latijn lapis = steen (vgl. lapis lazuli): de stift van grafiet.',
  'v.el-sobre': 'sobre = over, op: de envelop gaat óver de brief.',
  'v.el-pegamento': 'Van pegar = plakken.',
  'v.el-rotulador': 'el rótulo = het opschrift: de stift voor opschriften.',
  'v.el-sacapuntas': 'saca + puntas: "haalt punten uit". ' + COMPOUND,
  'v.la-cinta-adhesiva': 'la cinta = het lint; adhesivo = klevend.',
  'v.la-goma-de-borrar': 'borrar = uitvegen, wissen.',
  'v.la-hoja': F_TO_H + 'Latijn folia (vgl. folie) → hoja. Ook het blad van een boom.',
  'v.la-papelera': 'el papel + -era (houder): de bak voor papier.',
  'v.la-regla': 'De regel én de lineaal: waarmee je een rechte lijn trekt.',
  'v.la-carpeta': 'Valse vriend: geen carpet (dat is la alfombra), maar een map.',
  'v.el-calendario': 'Vgl. Engels calendar.',

  /* --- winkels --- */
  'v.la-drogueria': 'Valse vriend: geen drugs, maar huishoud- en verzorgingsproducten.',
  'v.la-tintoreria': 'Van teñir/tinte = verven: vroeger een ververij.',
  'v.los-grandes-almacenes': 'el almacén = het magazijn, uit het Arabisch al-makhzan (Frans magasin).',
  'v.el-mercadillo': 'Verkleinwoord van el mercado: het "marktje".',

  /* --- natuur en reizen --- */
  'v.el-mono': 'el mono = de aap, maar ¡qué mono! = wat schattig!',
  'v.el-pueblo': 'Vgl. Engels people: het dorp én het volk.',
  'v.el-gato': 'Vgl. Frans chat.',
  'v.la-mariposa': 'Uit "María, posa": Maria, ga zitten — zoals een vlinder op een bloem.',
  'v.el-mosquito': 'Verkleinwoord van la mosca (de vlieg): het vliegje.',
  'v.el-crucero': 'Van cruzar = oversteken, de zee doorkruisen.',
  'v.el-equipaje': 'Vgl. Engels equipment, Frans équipage.',
  'v.el-albergue': 'Vgl. Frans auberge, Duits Herberge.',
  'v.el-la-peregrino-a': 'Vgl. Engels pilgrim, Frans pèlerin.',
  'v.la-paz': 'Vgl. Frans paix, Engels peace.',
  'v.las-comodidades': 'Van cómodo = comfortabel.',
  'v.comodo-a': 'Vgl. Frans commode: handig, gemakkelijk.',

  /* --- bijvoeglijke naamwoorden, kleuren --- */
  'v.pobre': 'Vgl. Engels poor, Frans pauvre.',
  'v.regular': '¿Qué tal? — Regular. = Gaat wel. In de omgangstaal is het "middelmatig".',
  'v.azul': 'Vgl. azuur (Côte d\'Azur).',
  'v.marron': 'Vgl. Frans marron (kastanje).',
  'v.rojo-a': 'Vgl. Frans rouge.',
  'v.blanco-a': 'Vgl. Frans blanc.',
  'v.morado-a': 'la mora = de braam: paars als een braam.',
  'v.mayor': 'Vgl. Engels major. Ook ouder: mi hermano mayor.',
  'v.peor': 'Vgl. pejoratief.',

  /* --- bijwoorden, kleine woorden --- */
  'v.aqui': THREE_PLACES,
  'v.ahi': THREE_PLACES,
  'v.alli': THREE_PLACES,
  'v.aun': 'Met accent (aún) = nog; zonder accent (aun) = zelfs.',
  'v.siempre': 'Uit Latijn semper (vgl. semper fidelis).',
  'v.tampoco': 'Het "ook" na een ontkenning: A mí no me gusta. — A mí tampoco.',
  'v.tambien': 'Het "ook" na een bevestiging: Me gusta. — A mí también.',
  'v.nunca': N_WORDS,
  'v.nada': N_WORDS,
  'v.nadie': N_WORDS,
  'v.ninguno-a': N_WORDS,
  'v.algo': N_WORDS,
  'v.alguien': N_WORDS,
  'v.alguno-a': N_WORDS,
  'v.manana': 'mañana por la mañana = morgenochtend.',
  'v.enfrente-de': 'la frente = het voorhoofd: recht voor je hoofd.',
  'v.a-la-derecha-de': 'derecho = recht: rechts, net als in het Nederlands.',
  'v.debajo-de': 'bajo = laag, onder.',
  'v.detras-de': 'tras = na, achter.',

  /* --- vraagwoorden --- */
  'v.por-que': '¿Por qué? (los, met accent) = waarom; porque (aan elkaar) = omdat.',
  'v.adonde': 'a + dónde: naar waar.',
  'v.de-donde': 'de + dónde: van waar.',

  /* --- getallen --- */
  'v.once': TEENS,
  'v.doce': TEENS,
  'v.trece': TEENS,
  'v.catorce': TEENS,
  'v.quince': TEENS,
  'v.dieciseis': 'dieci- + seis: "tien en zes". Zo ook diecisiete, dieciocho, diecinueve.',
  'v.cuarenta': TENS,
  'v.cincuenta': TENS,
  'v.sesenta': TENS,
  'v.setenta': TENS,
  'v.ochenta': TENS,
  'v.noventa': TENS,
};
